server.port=8081

spring.application.name=ms-auth

spring.datasource.url=jdbc:mysql://localhost:3306/ms_auth_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=aduanas_secret_key_2024_muy_segura
jwt.expiration=86400000